/**
 * Zomi Catholic Community Directory
 * Data from https://kmuang.github.io/cd/
 */

export interface Member {
  name: string;
  role?: string;
}

export interface CommunityLeader {
  role: string;
  name: string;
}

export interface Household {
  id: string;
  householdName: string;
  members: Member[];
  address: string;
  city: string;
  state: string;
  zip: string;
  phone: string;
  phoneAlt?: string;
  group: string;
}

export const COMMUNITY_LEADERS: CommunityLeader[] = [
  { role: 'Parish Pastor', name: 'Fr. Robert Kim Pu' },
  { role: 'Parish Pastor', name: 'Paul Pau Cin' },
  { role: 'Parish Catechist', name: 'John The Baptist Zam Kim Thang' },
  { role: 'Parish Catechist', name: 'Isidore Nang Than Lian' },
  { role: 'President', name: 'Matthias Pau Kap Thang' },
  { role: 'Vice-President', name: 'Thawng Dong Kam, Paul' },
  { role: 'Secretary', name: 'Suan Khan Kap, Thomas' },
  { role: 'Assistant-Secretary', name: 'Niang Nu' },
  { role: 'Treasurer', name: 'Hau Za Niang, Angela' },
];

export const DIRECTORY_GROUPS = [
  'Community Leaders',
  'St. Matthew',
  'St. Mark',
  'St. Luke',
  'St. John',
  'St. Paul',
  'St. Joseph',
  'St. Peter',
  'N/A',
] as const;

export const DIRECTORY_DATA: Household[] = [
  // ═══════════════════════════════════════
  // ST. MATTHEW
  // ═══════════════════════════════════════
  {
    id: 'stm-1',
    group: 'St. Matthew',
    householdName: 'Felix Dal Suan Lian',
    members: [
      { name: 'Felix Dal Suan Lian' },
      { name: 'Esther Cing Hau Nuam' },
      { name: 'Agatha Muaan Lawh Muang' },
      { name: 'David Mung Lian Khup' },
    ],
    address: '450 E 148th St S',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '918-807-2867',
    phoneAlt: '918-671-9843',
  },
  {
    id: 'stm-2',
    group: 'St. Matthew',
    householdName: 'Marcus Go Suan Tung',
    members: [
      { name: 'Marcus Go Suan Tung' },
      { name: 'Elizabeth Awi Suan Niang' },
      { name: 'Joseph Dal Khan Kim' },
      { name: 'Peter Thang Sian Sang' },
      { name: 'Anna Niang Zo Kim' },
      { name: 'Veronica Luan Do Man' },
      { name: 'John Thawng Kap Pau' },
      { name: 'John Lang Khen Mung' },
    ],
    address: '14962 S Oak St',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '512-507-6405',
  },
  {
    id: 'stm-3',
    group: 'St. Matthew',
    householdName: 'David Tual Lian Thawn',
    members: [
      { name: 'David Tual Lian Thawn' },
      { name: 'Rose Man Khen Cing' },
      { name: 'Peter Thang Kim Lai' },
      { name: 'Mary Ciin Ban Kim' },
      { name: 'Victor Nung Sian Sum Naupa' },
      { name: 'Stephen Do Kim Sang' },
    ],
    address: '710 E 148th PL S',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '918-863-4779',
  },
  {
    id: 'stm-4',
    group: 'St. Matthew',
    householdName: 'John Do Lian Mung',
    members: [
      { name: 'John Do Lian Mung' },
      { name: 'Monica Dim Sian Hoih' },
      { name: 'Cecilia Cin Lun Niang' },
      { name: 'Esther Cing Hau Ciang' },
    ],
    address: '1174 E 146th Ct S',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '918-853-8302',
  },
  {
    id: 'stm-5',
    group: 'St. Matthew',
    householdName: 'Francis Thang Lam Thawn',
    members: [
      { name: 'Francis Thang Lam Thawn' },
      { name: 'Michael Nang lam Sing' },
      { name: 'Martha Dim Zam Huai' },
      { name: 'Bosco Nang Pian Mung' },
      { name: 'Regina Cing Lawh Nuam' },
    ],
    address: '14736 S Fern PL',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '918-900-7182',
    phoneAlt: '918-982-0944',
  },
  {
    id: 'stm-6',
    group: 'St. Matthew',
    householdName: 'Gabriel Zam Kap Thang',
    members: [
      { name: 'Gabriel Zam Kap Thang' },
      { name: 'Angela Cing Suan Zen' },
      { name: 'John Hau Za Pau' },
      { name: 'Cecilia Cing En Vung' },
    ],
    address: '14641 S Maple Ave',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '616-589-9867',
  },
  {
    id: 'stm-7',
    group: 'St. Matthew',
    householdName: 'Dominic Suang Gin Tung',
    members: [
      { name: 'Dominic Suang Gin Tung' },
      { name: 'Cecilia Cing Nun Nuam' },
      { name: 'Moses Thang San Ging' },
      { name: 'Jacob Go Ngaih Vaabn' },
    ],
    address: '7825 S Wheeling Ave Apt 37D',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-428-5285',
  },
  {
    id: 'stm-8',
    group: 'St. Matthew',
    householdName: 'Mark Nang Sian Pau',
    members: [
      { name: 'Mark Nang Sian Pau' },
      { name: 'Athaben Mang Sawm Lian' },
      { name: 'Isaac Dim Suan Mung' },
      { name: 'David Ngo Sawm Thang' },
      { name: 'Monica Dim San Cing' },
    ],
    address: '14769 S Fern Pl',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '918-889-6873',
  },
  {
    id: 'stm-9',
    group: 'St. Matthew',
    householdName: 'Jerome Kap Sian Khai',
    members: [
      { name: 'Jerome Kap Sian Khai' },
      { name: 'Joseph Thang Sian Lian' },
      { name: 'Esther Man Lun Niang' },
      { name: 'Cecilia Cing Ngaih Vung' },
    ],
    address: '14796 S Glenn St',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '972-974-4698',
  },
  {
    id: 'stm-10',
    group: 'St. Matthew',
    householdName: 'Romanus Khai Lam Thawn',
    members: [
      { name: 'Romanus Khai Lam Thawn' },
      { name: 'Annunciata Niang San Cing' },
      { name: 'Elizabeth Cing Nop Dim' },
      { name: 'Monica Ciang Lun Huai' },
      { name: 'Theophilus Mang ngel Siam' },
    ],
    address: '3309 E 143rd Pl S',
    city: 'Bixby',
    state: 'OK',
    zip: '',
    phone: '918-986-6525',
  },
  {
    id: 'stm-11',
    group: 'St. Matthew',
    householdName: 'Augustine Pau Ngaih Khual',
    members: [
      { name: 'Augustine Pau Ngaih Khual' },
      { name: 'Mary Thang Kuam Don' },
      { name: 'Anna Cing Sian Deih' },
      { name: 'David Gin Sian Vaan' },
      { name: 'Helenna Man Sian Hoih' },
      { name: 'Justina Tual Lam Niang' },
      { name: 'Simon Thang Deih Khual' },
      { name: 'Moses Lian Sian Khai' },
    ],
    address: '14744 S Fern PL',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '918-845-2958',
  },
  {
    id: 'stm-12',
    group: 'St. Matthew',
    householdName: 'Thomas Thang Khan Thawn',
    members: [
      { name: 'Thomas Thang Khan Thawn' },
      { name: 'Theresa Cing Tawi Siam' },
      { name: 'Esther Lian Muan Cing' },
      { name: 'Elizabeth Zen Sian Kim' },
      { name: 'John Thang Suan Mung' },
      { name: 'David Pau Deih Piang' },
    ],
    address: '14747 S Glenn St',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '918-640-6142',
  },
  {
    id: 'stm-13',
    group: 'St. Matthew',
    householdName: 'Andrew Pau Khan Khual',
    members: [
      { name: 'Andrew Pau Khan Khual' },
      { name: 'Rita Lian Lawh Nuam' },
      { name: 'Francis Langh Khan Thang' },
      { name: 'David Do En Sing' },
      { name: 'Jerome Pau Kop Van' },
    ],
    address: '689 E 149th St S',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '918-344-2431',
  },
  {
    id: 'stm-14',
    group: 'St. Matthew',
    householdName: 'Francis Khup Lem Piang',
    members: [
      { name: 'Francis Khup Lem Piang' },
      { name: 'Andrew Sum Hau Mung' },
      { name: 'John Mang Sawm Sang' },
      { name: 'Maria Ciin Lam Cing' },
      { name: 'Anna Don It Nuam' },
      { name: 'Maria Cing Za Don' },
    ],
    address: '502 E 147th ST S',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '918-284-1372',
  },
  {
    id: 'stm-15',
    group: 'St. Matthew',
    householdName: 'Sylverius Go Khan Gin',
    members: [
      { name: 'Sylverius Go Khan Gin' },
      { name: 'Robert Thang Pian Khai' },
      { name: 'Niang Deih Ciin' },
      { name: 'Daniel Mung Suan Khual' },
      { name: 'Lawrence Suan Kop Lal' },
      { name: 'Angela Cing Deih Muang' },
    ],
    address: '732 E 147th St S',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '918-619-5261',
  },
  {
    id: 'stm-16',
    group: 'St. Matthew',
    householdName: 'William Pum Tul Tuang',
    members: [
      { name: 'William Pum Tul Tuang' },
      { name: 'Angela Dim Ngun Cing' },
    ],
    address: '14632 S Maple Ave',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '918-852-3281',
  },
  {
    id: 'stm-17',
    group: 'St. Matthew',
    householdName: 'John Pau Muan Sum',
    members: [
      { name: 'John Pau Muan Sum' },
      { name: 'Sian Khan Sum' },
      { name: 'John Khup Lam Thang' },
      { name: 'Veronica Mang Hen Cing' },
      { name: 'Peter Nang Tuah Thang' },
    ],
    address: '14755 S Ferm Pl',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '757-912-2662',
  },
  {
    id: 'stm-18',
    group: 'St. Matthew',
    householdName: 'Luke Mang Mun Shwe',
    members: [
      { name: 'Luke Mang Mun Shwe' },
      { name: 'Martha Zen Suan Niang' },
    ],
    address: '1004 E 148th St',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '918-629-3346',
    phoneAlt: '918-691-9842',
  },
  {
    id: 'stm-19',
    group: 'St. Matthew',
    householdName: 'John the Baptist Zam Kim Thang',
    members: [
      { name: 'John the Baptist Zam Kim Thang' },
      { name: 'Lucy Ning Suan Mang' },
      { name: 'Veronica Vung Sian Huai' },
      { name: 'Francis Mung Deih Khai' },
    ],
    address: '1039 E 148th St',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '918-904-8329',
  },
  {
    id: 'stm-20',
    group: 'St. Matthew',
    householdName: 'James Thuam Khan Kim',
    members: [
      { name: 'James Thuam Khan Kim' },
      { name: 'Ruth Niang Zam Lun' },
      { name: 'Stephen Mung Van Tuang' },
      { name: 'Martha Man Liim Nuam' },
    ],
    address: '7008 E 155th St S',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '704-769-9439',
  },
  {
    id: 'stm-21',
    group: 'St. Matthew',
    householdName: 'Andrew Pau Khan Hau',
    members: [
      { name: 'Andrew Pau Khan Hau' },
      { name: 'Cecilia Luan Lam Ciang' },
      { name: 'Thomas Lian Mang' },
      { name: 'Emily Niang Muang Cing' },
      { name: 'Paul Thang Khup' },
      { name: 'Theresa Man Hoih Kim' },
    ],
    address: '7118 E 155th St S',
    city: 'Bixby',
    state: 'OK',
    zip: '',
    phone: '918-933-7859',
    phoneAlt: '918-934-2148',
  },
  {
    id: 'stm-22',
    group: 'St. Matthew',
    householdName: 'Martin Kap Khan Khup',
    members: [
      { name: 'Martin Kap Khan Khup' },
      { name: 'Dim Lawh Cing' },
      { name: 'Francis Mang Sian Khai' },
    ],
    address: '6283 E 147th St S',
    city: 'Bixby',
    state: 'OK',
    zip: '',
    phone: '918-344-8303',
  },
  {
    id: 'stm-23',
    group: 'St. Matthew',
    householdName: 'Michael Cin Khan Khual',
    members: [
      { name: 'Michael Cin Khan Khual' },
      { name: 'Agatha Niang Ngo Lun' },
    ],
    address: '14038 S Madison Ave',
    city: 'Bixby',
    state: 'OK',
    zip: '',
    phone: '918-645-5346',
  },
  {
    id: 'stm-24',
    group: 'St. Matthew',
    householdName: 'Paul Ye lin Aung',
    members: [
      { name: 'Paul Ye lin Aung' },
      { name: 'Cynthia Su Shin Thant' },
      { name: 'Maria Huai Ngaih Lun' },
      { name: 'Joseph Zaw Myint (Nay Win)' },
    ],
    address: '4605 E 143rd St S',
    city: 'Bixby',
    state: 'OK',
    zip: '',
    phone: '539-218-5247',
  },
  {
    id: 'stm-25',
    group: 'St. Matthew',
    householdName: 'Edward Hau Suan Mung',
    members: [
      { name: 'Edward Hau Suan Mung' },
      { name: 'Maria Cin Sian Huai' },
      { name: 'Anna Cin Khan Nuam' },
      { name: 'Francis Khai Mun Kung' },
      { name: 'Lucy Cing San Kim' },
      { name: 'Catherine Zen Lam Cing' },
    ],
    address: '7408 E 155th Pl S',
    city: 'Bixby',
    state: 'OK',
    zip: '',
    phone: '620-521-7445',
  },
  {
    id: 'stm-26',
    group: 'St. Matthew',
    householdName: 'Francis Mang Khan Khen',
    members: [
      { name: 'Francis Mang Khan Khen' },
      { name: 'Emily Lun Khan Nuam' },
      { name: 'Rita Nuam Deih Muan' },
    ],
    address: '6253 E 147th St S',
    city: 'Bixby',
    state: 'OK',
    zip: '',
    phone: '918-378-1449',
  },
  {
    id: 'stm-27',
    group: 'St. Matthew',
    householdName: 'Paul Sian Za Pum',
    members: [{ name: 'Paul Sian Za Pum' }],
    address: '7543 E 158th St S',
    city: 'Bixby',
    state: 'OK',
    zip: '',
    phone: '918-500-0077',
  },
  {
    id: 'stm-28',
    group: 'St. Matthew',
    householdName: 'Lucy Nem Do Man',
    members: [{ name: 'Lucy Nem Do Man' }],
    address: '1318 E 133rd Pl',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '918-951-2234',
  },
  {
    id: 'stm-29',
    group: 'St. Matthew',
    householdName: 'Cecilia Hau Khawl Nuam',
    members: [{ name: 'Cecilia Hau Khawl Nuam' }],
    address: '14775 S Farn Pl',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '224-856-7112',
  },
  {
    id: 'stm-30',
    group: 'St. Matthew',
    householdName: 'Aloysius Mang Muan Lian',
    members: [
      { name: 'Aloysius Mang Muan Lian' },
      { name: 'Paul Lam Sawm Tung' },
      { name: 'Veronica Lun Ngaih Nuam Kim' },
    ],
    address: '1030 E 148th St',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '918-884-4970',
    phoneAlt: '817-615-7348',
  },
  {
    id: 'stm-31',
    group: 'St. Matthew',
    householdName: 'Martin Thang Khat Khai Guite',
    members: [
      { name: 'Martin Thang Khat Khai Guite' },
      { name: 'Veronica Cing Suan Muang' },
      { name: 'Jacob Kap Tung Tuang' },
      { name: 'Esther Hau Khan Lun' },
    ],
    address: '14725 S Hickory St',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '630-597-8599',
    phoneAlt: '630-703-5815',
  },
  // ═══════════════════════════════════════
  // ST. MARK
  // ═══════════════════════════════════════
  {
    id: 'stmk-1',
    group: 'St. Mark',
    householdName: 'John Khup Lam Mang',
    members: [
      { name: 'John Khup Lam Mang' },
      { name: 'Paul Ai Lian Pau' },
    ],
    address: '7809 S Wheeling Ave #29L',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-889-3304',
  },
  {
    id: 'stmk-2',
    group: 'St. Mark',
    householdName: 'Hlun Kho Mang',
    members: [
      { name: 'Hlun Kho Mang' },
      { name: 'Rosa Chin Neilhing Haokip' },
      { name: 'Samuel Hou Minlen Haokip' },
      { name: 'Rebacca Vah Pahhoi Haukip' },
      { name: 'Asumpta Neng NgaihKim Haokip' },
    ],
    address: '9226 E 95th St',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-384-9565',
  },
  {
    id: 'stmk-3',
    group: 'St. Mark',
    householdName: 'Lucy Thang Ngaih Man',
    members: [
      { name: 'Lucy Thang Ngaih Man' },
      { name: 'Scholastica Ciin Muan Khawm' },
      { name: 'Monica Lian Hau Cing' },
      { name: 'Helena Lun San Cing' },
      { name: 'Joseph Zam Suan Mung' },
    ],
    address: '13156 S 92nd E Ave',
    city: 'Bixby',
    state: 'OK',
    zip: '',
    phone: '954-336-3868',
  },
  {
    id: 'stmk-4',
    group: 'St. Mark',
    householdName: 'Emillic Ngin Kang Lo',
    members: [
      { name: 'Emillic Ngin Kang Lo' },
      { name: 'Michael Lian Muan Kham' },
      { name: 'Emily Ning Sian Lun' },
      { name: 'Veronica Cing Dim Uap' },
      { name: 'Felix Vai Sian Tuang' },
    ],
    address: '1543 E 77th St',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-605-7689',
  },
  {
    id: 'stmk-5',
    group: 'St. Mark',
    householdName: 'Abraham Kai Khen Pau',
    members: [
      { name: 'Abraham Kai Khen Pau' },
      { name: 'Lucy Man Ngaih Nuam' },
      { name: 'Margret Niangh Gin Man' },
      { name: 'Theresa Cing Gel Mang' },
      { name: 'Emily Cing Sian Sang' },
    ],
    address: '1548 E 75th Ct',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-816-6725',
  },
  {
    id: 'stmk-6',
    group: 'St. Mark',
    householdName: 'Timothy Tong Kho Sei (Zam Khan Khup)',
    members: [
      { name: 'Timothy Tong Kho Sei' },
      { name: 'Joanne Dim Lung Dei Lhing' },
      { name: 'Lucia Dim Kho Tin' },
      { name: 'Judith Cing Sian Lun' },
      { name: 'Julia Paonom Kim' },
      { name: 'Monica Lhing Boi' },
      { name: 'Bosco Kap Thang' },
    ],
    address: '707 N Butternut Ct',
    city: 'Broken Arrow',
    state: 'OK',
    zip: '',
    phone: '918-902-4617',
  },
  {
    id: 'stmk-7',
    group: 'St. Mark',
    householdName: 'Peter Khup Mung',
    members: [
      { name: 'Peter Khup Mung' },
      { name: 'Joana Cing Zam Niang' },
      { name: 'Francis Khup Pian Sing' },
    ],
    address: '9207 S Maplewood Ave',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '413-241-9543',
  },
  {
    id: 'stmk-8',
    group: 'St. Mark',
    householdName: 'Peter Gin Khan Khai',
    members: [
      { name: 'Peter Gin Khan Khai' },
      { name: 'Maria Lun Sian Muang' },
      { name: 'John Lian Tung Piang' },
      { name: 'Joseph Mang Mun Sang' },
      { name: 'Dim Sian Lun' },
    ],
    address: '8501 E 93rd St',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-851-7640',
  },
  {
    id: 'stmk-9',
    group: 'St. Mark',
    householdName: 'Michael Mang Thong Haokip',
    members: [
      { name: 'Michael Mang Thong Haokip' },
      { name: 'Francis Xavier Pum Min Lal Haokip' },
      { name: 'Madarena Tin Neih Lam Haokip' },
      { name: 'Teresa Hat ngai Kim' },
    ],
    address: '11886 S 99th E Ave',
    city: 'Bixby',
    state: 'OK',
    zip: '',
    phone: '918-527-5352',
    phoneAlt: '918-924-4440',
  },
  {
    id: 'stmk-10',
    group: 'St. Mark',
    householdName: 'John Lhun Min Thang',
    members: [
      { name: 'John Lhun Min Thang' },
      { name: 'Tim Nei Chong' },
      { name: 'Henlena Lam Nei Them' },
      { name: 'Miximilion Thawng Min Lun' },
    ],
    address: '9415 E 95th Pl',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '539-593-6243',
    phoneAlt: '918-859-9983',
  },
  {
    id: 'stmk-11',
    group: 'St. Mark',
    householdName: 'Anthony Thawng Sian Tuang',
    members: [
      { name: 'Anthony Thawng Sian Tuang' },
      { name: 'Esther Vung Tawi Par' },
      { name: 'Man Nun Huai' },
    ],
    address: '',
    city: '',
    state: '',
    zip: '',
    phone: '',
  },
  {
    id: 'stmk-12',
    group: 'St. Mark',
    householdName: 'Isidore Thang Sian Tung',
    members: [
      { name: 'Isidore Thang Sian Tung' },
      { name: 'Peter Neng Deih Piang' },
      { name: 'Agatha Ning Ngaih Ciin' },
      { name: 'Zen Sawm Cing' },
    ],
    address: '7610 S Trenton Ave',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-853-0939',
  },
  {
    id: 'stmk-13',
    group: 'St. Mark',
    householdName: 'Augustine Thong Kho Sei',
    members: [
      { name: 'Augustine Thong Kho Sei' },
      { name: 'Henry Sei Len Cung' },
      { name: 'Maria Nieng Nei Thiem' },
      { name: 'Francis Assisi Sei Gou Sang' },
      { name: 'Angela Lam Hoi Kim' },
    ],
    address: '9319 S 95th E PL',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '539-525-2028',
    phoneAlt: '539-235-9487',
  },
  {
    id: 'stmk-14',
    group: 'St. Mark',
    householdName: 'Paul Thawng Dong Kam',
    members: [{ name: 'Paul Thawng Dong Kam' }],
    address: '2621 E 88th St Apt#',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '',
  },
  {
    id: 'stmk-15',
    group: 'St. Mark',
    householdName: 'Pius Thang Ngaih Lian',
    members: [{ name: 'Pius Thang Ngaih Lian' }],
    address: '7921 S Wheeling Ave Apt 51P',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-861-2269',
  },
  {
    id: 'stmk-16',
    group: 'St. Mark',
    householdName: 'John Mung Za Pau',
    members: [
      { name: 'John Mung Za Pau' },
      { name: 'Niang Deih Lun' },
      { name: 'Man Huai Sung' },
    ],
    address: '8002 S Wheeling Ave Apt N',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-804-5289',
  },
  {
    id: 'stmk-17',
    group: 'St. Mark',
    householdName: 'John Zoo Pau',
    members: [
      { name: 'John Zoo Pau' },
      { name: 'Anna Hau Khawl Nuam' },
      { name: 'Elizabeth Siam Ngaih Huai' },
      { name: 'Peter Thang Muan Lian' },
    ],
    address: '7907 S Wheeling Ave #41 M',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-550-9845',
  },
  {
    id: 'stmk-18',
    group: 'St. Mark',
    householdName: 'James Kam Sawm Thang',
    members: [
      { name: 'James Kam Sawm Thang' },
      { name: 'Michael Hang Muan Mung' },
      { name: 'Theresa Cing Khawl Muang' },
      { name: 'Martha Niang tawi It' },
      { name: 'Valentina Ngai San Nuam' },
      { name: 'Enoch Mang Sian Khual' },
    ],
    address: '8212 S Florence PL C',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '919-590-2190',
    phoneAlt: '918-688-0944',
  },
  {
    id: 'stmk-19',
    group: 'St. Mark',
    householdName: 'Henry Thang Suan Dal',
    members: [
      { name: 'Henry Thang Suan Dal' },
      { name: 'Lucy Ning Suan Mang' },
      { name: 'Veronica Vung Sian Huai' },
      { name: 'Francis Mung Deih Khai' },
    ],
    address: '',
    city: 'Bixby',
    state: 'OK',
    zip: '',
    phone: '',
  },
  {
    id: 'stmk-20',
    group: 'St. Mark',
    householdName: 'John Al Deih Piang',
    members: [
      { name: 'John Al Deih Piang' },
      { name: 'Theresa Cing Tawi Lun' },
      { name: 'Susana Cing San Nem' },
      { name: 'Rita Go Zam Vung' },
      { name: 'Mang Sian Hoih' },
      { name: 'Paul Cin Sawm Lian' },
    ],
    address: '2512 E 88th St #1',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '806-676-6509',
    phoneAlt: '539-867-9034',
  },
  {
    id: 'stmk-21',
    group: 'St. Mark',
    householdName: 'Jude Tuangneu',
    members: [
      { name: 'Jude Tuangneu' },
      { name: 'Bibiana Niang Ngaih Mang' },
      { name: 'Jason Mung Huam Zo' },
      { name: 'Jack Lian Muan Thang' },
      { name: 'James Lai Muan Vaan' },
    ],
    address: '7361 E 119th PL S',
    city: 'Bixby',
    state: 'OK',
    zip: '',
    phone: '919-758-9733',
    phoneAlt: '919-879-7155',
  },
  {
    id: 'stmk-22',
    group: 'St. Mark',
    householdName: 'Lucas Thang Pian Hau',
    members: [{ name: 'Lucas Thang Pian Hau' }],
    address: '2986 E 77th St',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-645-0556',
  },
  {
    id: 'stmk-23',
    group: 'St. Mark',
    householdName: 'Pa Lian Cung Nawl',
    members: [
      { name: 'Pa Lian Cung Nawl' },
      { name: 'Kam Ngaih Huai' },
      { name: 'Isaac Biak Lian Cung' },
      { name: 'Phillip Dai Sian Sang' },
      { name: 'David Lam Tang Lian' },
    ],
    address: '7334 S Victor Ave',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '539-222-8377',
    phoneAlt: '539-222-8755',
  },
  {
    id: 'stmk-24',
    group: 'St. Mark',
    householdName: 'Andrew Gin Lian Hang',
    members: [
      { name: 'Andrew Gin Lian Hang' },
      { name: 'Mary Vung Lawh Dim' },
    ],
    address: '7361 E 119th Pl S',
    city: 'Bixby',
    state: 'OK',
    zip: '',
    phone: '919-817-6167',
  },
  {
    id: 'stmk-25',
    group: 'St. Mark',
    householdName: 'Peter Pau Suan Mang',
    members: [
      { name: 'Peter Pau Suan Mang' },
      { name: 'Maria Zen Don Vung' },
    ],
    address: '2707 E 88th St Apt 660',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-346-9057',
  },
  {
    id: 'stmk-26',
    group: 'St. Mark',
    householdName: 'Petru Tuang',
    members: [
      { name: 'Petru Tuang' },
      { name: 'Emily Lun Khan Nuam' },
      { name: 'Rita Nuam Deih Muan' },
    ],
    address: '7819 S Wheeling Ave Apt 44E',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '',
  },
  {
    id: 'stmk-27',
    group: 'St. Mark',
    householdName: 'John Lian',
    members: [
      { name: 'John Lian' },
      { name: 'Philomena Cing Deih' },
      { name: 'Clare Cing Sian Sung' },
    ],
    address: '8015 S Wheeling Ave Apt# F',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '',
  },
  {
    id: 'stmk-28',
    group: 'St. Mark',
    householdName: 'Bosco Kap Thang Touthang',
    members: [
      { name: 'Bosco Kap Thang Touthang' },
      { name: 'Bibiana Cin Nei Neng' },
      { name: 'Michael Khup Then Sei Touthang' },
    ],
    address: '7607 E 89th PL',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-204-2931',
  },
  {
    id: 'stmk-29',
    group: 'St. Mark',
    householdName: 'Phillip Pau Khan Mang',
    members: [
      { name: 'Phillip Pau Khan Mang' },
      { name: 'Martha Khup Deih Niang' },
      { name: 'John Thang Kap Lal' },
    ],
    address: '2108 E 82nd Ct',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-829-2772',
  },
  {
    id: 'stmk-30',
    group: 'St. Mark',
    householdName: 'Augustine Khup Suan Hau',
    members: [
      { name: 'Augustine Khup Suan Hau' },
      { name: 'Monica Khawl San Nuam' },
      { name: 'Veronica Niang San Vung' },
      { name: 'Jude Thang Sien Kam' },
    ],
    address: '1030 E 148th St',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '918-304-4537',
    phoneAlt: '918-304-0675',
  },
  {
    id: 'stmk-31',
    group: 'St. Mark',
    householdName: 'Peter Pau Sian Mang',
    members: [
      { name: 'Peter Pau Sian Mang' },
      { name: 'Agnes Palnu' },
      { name: 'Vincent Dal Muan Lian' },
      { name: 'Florence Cing Sian Hung' },
    ],
    address: '12404 S Oxford Ave',
    city: 'Bixby',
    state: 'OK',
    zip: '',
    phone: '918-932-5669',
    phoneAlt: '918-712-0682',
  },
  {
    id: 'stmk-32',
    group: 'St. Mark',
    householdName: 'Dominic Thang Khan Piang',
    members: [
      { name: 'Dominic Thang Khan Piang' },
      { name: 'Lucy Vung Muan Kim' },
      { name: 'Joseph Kap Thon Kim' },
    ],
    address: '2507 E 88th St',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '539-281-5291',
  },
  {
    id: 'stmk-33',
    group: 'St. Mark',
    householdName: 'Thomas Kham Hau Lian',
    members: [
      { name: 'Thomas Kham Hau Lian' },
      { name: 'Monica Niang Khawm Cing' },
      { name: 'Emily Nian Sian Huai' },
      { name: 'Esther Vung It Ciang' },
    ],
    address: '8015 S Wheeling Apt 0',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-361-5530',
  },
  {
    id: 'stmk-34',
    group: 'St. Mark',
    householdName: 'Michael Khup Tul Mung',
    members: [
      { name: 'Michael Khup Tul Mung' },
      { name: 'Maria Mou Wah Kyee' },
      { name: 'Cing Lam Lun' },
      { name: 'Cing Lian Piang' },
      { name: 'Lian Sian Hoih Muang' },
      { name: 'Piang Ngaih' },
      { name: 'Piang Kim Mung' },
    ],
    address: '8003 S Wheeling Ave Apt C',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '539-910-6764',
  },
  {
    id: 'stmk-35',
    group: 'St. Mark',
    householdName: 'Bosco Khup Khan Lal',
    members: [
      { name: 'Bosco Khup Khan Lal' },
      { name: 'Kangnu Rosa' },
      { name: 'Gerrard Mung Len Sang' },
      { name: 'Stephen Khual Biak Thang' },
      { name: 'Lucas Tuang Bawi Lian' },
      { name: 'Kate Nuam Lawh Sian' },
    ],
    address: '7905 S Wheeling Ave Apt 42K',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-804-3654',
  },
  {
    id: 'stmk-36',
    group: 'St. Mark',
    householdName: 'Elizabeth Kachin',
    members: [{ name: 'Elizabeth Kachin' }],
    address: '2539 E 88th St Apt 626',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '',
  },
  // ═══════════════════════════════════════
  // ST. LUKE
  // ═══════════════════════════════════════
  {
    id: 'stl-1',
    group: 'St. Luke',
    householdName: 'Rosa Awi Khan Niang',
    members: [
      { name: 'Rosa Awi Khan Niang' },
      { name: 'Michael Dong Suan Mung' },
    ],
    address: '815 N Birmingham Ave',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-586-2097',
    phoneAlt: '918-606-3316',
  },
  {
    id: 'stl-2',
    group: 'St. Luke',
    householdName: 'Nicholas Zam Lian Khup',
    members: [
      { name: 'Nicholas Zam Lian Khup' },
      { name: 'Benedicta Awi Khan Nuam' },
      { name: 'Foustina Niang San Huai' },
      { name: 'Lucy Zen Mun Mang' },
      { name: 'Paul Pau Sian Muang' },
      { name: 'Michael Pau Hon Thang' },
    ],
    address: '2862 E Archer St',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-829-6901',
  },
  {
    id: 'stl-3',
    group: 'St. Luke',
    householdName: 'Peter Chin Lian Mang',
    members: [
      { name: 'Peter Chin Lian Mang' },
      { name: 'Jame En Sian Mung' },
      { name: 'Elizabeth Cing Sian T Sang' },
      { name: 'Joseph Thang K Suan Mang' },
      { name: 'Anna Cing Khen Niang' },
    ],
    address: '112 N Zunis Ave',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-954-0820',
    phoneAlt: '918-902-4557',
  },
  {
    id: 'stl-4',
    group: 'St. Luke',
    householdName: 'Joseph Dal Suan Lian',
    members: [
      { name: 'Joseph Dal Suan Lian' },
      { name: 'Maria Ciin Ngaih Vum' },
      { name: 'Judith Cing Nuam Mang' },
      { name: 'Augustine Kam Sawm Lian' },
      { name: 'Lucy Vum Sian Kem' },
      { name: 'Monica Cing Sian Nem' },
      { name: 'Patrick Langh Sian Taang' },
    ],
    address: '849 N Saint Louis Ave',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-644-8154',
    phoneAlt: '918-810-2920',
  },
  {
    id: 'stl-5',
    group: 'St. Luke',
    householdName: 'Francis Suan Lian San Mung',
    members: [
      { name: 'Francis Suan Lian San Mung' },
      { name: 'Cecilia Zen Tawi Cing' },
      { name: 'Emily Cing Muan Dim' },
      { name: 'Mary Lian Lun Cing' },
      { name: 'Monica Niang San Dim' },
      { name: 'Catherine Lian Kop Sang' },
      { name: 'Bosco Mung Sian Piang' },
    ],
    address: '154 N Delaware Pl',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-644-8154',
    phoneAlt: '918-810-2920',
  },
  {
    id: 'stl-6',
    group: 'St. Luke',
    householdName: 'John Langh Deih Tuang',
    members: [
      { name: 'John Langh Deih Tuang' },
      { name: 'Cecilia Cing Sian Len' },
      { name: 'Angela Man Hau Dim' },
      { name: 'Jerome Dallian Mang' },
      { name: 'Agnes Niang San Nem' },
      { name: 'Clare Man Sian Huai' },
    ],
    address: '1403 N Trenton Ave',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '918-934-2590',
    phoneAlt: '918-933-2458',
  },
  {
    id: 'stl-7',
    group: 'St. Luke',
    householdName: 'Maria Ning Khan Lian',
    members: [
      { name: 'Maria Ning Khan Lian' },
      { name: 'Peter Suan Pian Thang' },
      { name: 'Agnes Hau Lun Cing' },
      { name: 'Cecilia Cing Ngaih Ciin' },
      { name: 'Rosa Lun Deih Kim' },
      { name: 'Catherine Lian Sian Huai' },
    ],
    address: '907 N Birmingham Ave',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-335-9685',
    phoneAlt: '918-946-8344',
  },
  {
    id: 'stl-8',
    group: 'St. Luke',
    householdName: 'Francis Zam Khan Kim',
    members: [
      { name: 'Francis Zam Khan Kim' },
      { name: 'Joseph Lang Sian Mang' },
      { name: 'Angela Hau Za Niang' },
      { name: 'Michael Tual khan Dal' },
      { name: 'Clare Do Khan Cing' },
    ],
    address: '748 N Lewis PL',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-812-1504',
    phoneAlt: '918-851-0465',
  },
  {
    id: 'stl-9',
    group: 'St. Luke',
    householdName: 'David Suan Go Thang',
    members: [{ name: 'David Suan Go Thang' }],
    address: '718 N St Louis St',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-361-7839',
  },
  {
    id: 'stl-10',
    group: 'St. Luke',
    householdName: 'Wilfred Thang Sian Mang',
    members: [
      { name: 'Wilfred Thang Sian Mang' },
      { name: 'Benedicta Niang Suan Lun' },
      { name: 'Michael Lang Sian Muang' },
      { name: 'Mary Ciin Sian Cing' },
      { name: 'John the Baptist Khual Sian Kim' },
    ],
    address: '1235 N Trenton Ave',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '817-210-5972',
  },
  {
    id: 'stl-11',
    group: 'St. Luke',
    householdName: 'Martin Pau Kop',
    members: [{ name: 'Martin Pau Kop' }],
    address: '3291 E Easton St',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '602-820-0278',
  },
  {
    id: 'stl-12',
    group: 'St. Luke',
    householdName: 'Gin Lam Thawn',
    members: [
      { name: 'Gin Lam Thawn' },
      { name: 'Theresa Cing Tawi Siam' },
      { name: 'Esther Lian Muan Cing' },
      { name: 'Elizabeth Zen Sian Kim' },
      { name: 'John Thang Suan Mung' },
      { name: 'David Pau Deih Piang' },
    ],
    address: '849 N St Louis Ave',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '539-525-2485',
    phoneAlt: '539-292-5737',
  },
  // ═══════════════════════════════════════
  // ST. JOHN
  // ═══════════════════════════════════════
  {
    id: 'stj-1',
    group: 'St. John',
    householdName: 'Maximilian Don Gin Lian',
    members: [
      { name: 'Maximilian Don Gin Lian' },
      { name: 'Francis Kap Sian Muan' },
      { name: 'Teresa Awi San Nuam' },
      { name: 'Veronica Cing Khawm Kim' },
      { name: 'Elizabeth Cing Sian Lun' },
      { name: 'Titus Thang Lian Piang' },
      { name: 'Suang Zen Lian' },
    ],
    address: '14603 S Nyssa Pl',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '918-720-1315',
  },
  {
    id: 'stj-2',
    group: 'St. John',
    householdName: 'Noel Cin Lam Kim',
    members: [
      { name: 'Noel Cin Lam Kim' },
      { name: 'Maria Ciin Don Ning' },
      { name: 'Theresa Vung San Kim' },
      { name: 'Sarah Pau Sian Nem' },
      { name: 'Esther Khawl Sian Cing' },
      { name: 'Elizabeth Pau San Nuam' },
    ],
    address: '14780 S Hickory Pl',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '918-932-5242',
  },
  {
    id: 'stj-3',
    group: 'St. John',
    householdName: 'Robert Nang Lian Cin',
    members: [
      { name: 'Robert Nang Lian Cin' },
      { name: 'Esther Ciin Lun Niang' },
    ],
    address: '1327 E 146th St S',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '918-508-3092',
  },
  {
    id: 'stj-4',
    group: 'St. John',
    householdName: 'Benedict Khai Khan Tuang',
    members: [
      { name: 'Benedict Khai Khan Tuang' },
      { name: 'Cecilia Ciin San Lian' },
      { name: 'Raphael Cin Lam Thawn' },
      { name: 'Anna Zel Lam Vung' },
      { name: 'Lucy Cing Sian Nem' },
    ],
    address: '1663 E 140th Pl',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '918-809-1525',
  },
  {
    id: 'stj-5',
    group: 'St. John',
    householdName: 'Gregory Cin Kim Thang',
    members: [
      { name: 'Gregory Cin Kim Thang' },
      { name: 'Theresa Ciin Tawi Kim' },
      { name: 'Maria Cing Pian Lun' },
      { name: 'Michael Nang Lam Sang' },
      { name: 'Daniel Sing Sian Mung' },
    ],
    address: '13273 S Oak Pl',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '918-902-8264',
  },
  {
    id: 'stj-6',
    group: 'St. John',
    householdName: 'Francis Cin Lam Lian',
    members: [
      { name: 'Francis Cin Lam Lian' },
      { name: 'Lucy Tung Sawm Cing' },
      { name: 'John Thang Sian Tuang' },
      { name: 'David Kam Sian Khai' },
      { name: 'Monica Lun Lam Cing' },
    ],
    address: '1172 E 132nd PL',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '918-946-3570',
  },
  {
    id: 'stj-7',
    group: 'St. John',
    householdName: 'Linus Khup Sawm Mang',
    members: [
      { name: 'Linus Khup Sawm Mang' },
      { name: 'Cecilia Cin Sian Mang' },
      { name: 'Monica Dim Sian Paal' },
      { name: 'Theresa Khup Sian Sung' },
      { name: 'Veronica Luan Khan Kim' },
      { name: 'Martin Khai Lam Mung' },
    ],
    address: '14067 S Madison Ave',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '918-808-7183',
  },
  {
    id: 'stj-8',
    group: 'St. John',
    householdName: 'Theresa Niang Khan Ciin',
    members: [
      { name: 'Theresa Niang Khan Ciin' },
      { name: 'Angela Cing Don Siam' },
      { name: 'Magaret Cing Ngaih Sian' },
      { name: 'Monica Niang San Mang' },
      { name: 'Rebecea Lun Love Kim Tanghatzaw' },
      { name: 'Ngin Lian Mang' },
      { name: 'Elizabeth Ciin Sian Nuam' },
    ],
    address: '14037 S Lansing Ave',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '918-730-2555',
    phoneAlt: '918-851-2274',
  },
  {
    id: 'stj-9',
    group: 'St. John',
    householdName: 'Joseph Pau Khet Khai',
    members: [
      { name: 'Joseph Pau Khet Khai' },
      { name: 'Esther Man Don Kim' },
      { name: 'Jacob Kap En Lian Sang' },
      { name: 'Maria Cing Khan Teen' },
      { name: 'Christina Hau Sian Khawl' },
      { name: 'Cecilia Cing Lian Vung' },
      { name: 'Felix Thang Lian Kap' },
    ],
    address: '14668 S Maple Ave',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '918-813-2495',
    phoneAlt: '918-954-6751',
  },
  {
    id: 'stj-10',
    group: 'St. John',
    householdName: 'Matthias Pau Kap Thang',
    members: [
      { name: 'Matthias Pau Kap Thang' },
      { name: 'Peter Sawm Hau Cin' },
      { name: 'Margaret Lun Lek' },
      { name: 'Simon Thang Biak Khai' },
      { name: 'Mary Cing Khup Niang' },
      { name: 'Theresa Cing Sian Muang' },
    ],
    address: '1663 E 138th St',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '918-804-2047',
    phoneAlt: '918-779-7346',
  },
  {
    id: 'stj-11',
    group: 'St. John',
    householdName: 'Lucas Kham En Thang',
    members: [
      { name: 'Lucas Kham En Thang' },
      { name: 'James Pau Tung Thang' },
      { name: 'Anna Niang Sian Ngaih' },
      { name: 'John Mung Tup Kiim' },
      { name: 'Cecilia Nian Ngaih Cing' },
      { name: 'Elizabeth Cing Sian Hoih' },
      { name: 'Esther No Sian Muan' },
      { name: 'Theresa Lian Deih Cing' },
      { name: 'Mary Nuam Ngaih Kiim' },
    ],
    address: '14607 S Nyssa Pl',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '918-600-8825',
    phoneAlt: '918-845-4242',
  },
  {
    id: 'stj-12',
    group: 'St. John',
    householdName: 'Peter Kham En Tuang',
    members: [
      { name: 'Peter Kham En Tuang' },
      { name: 'Cecilia No Nuam Cing' },
      { name: 'Bosco Thang Deih Sang' },
      { name: 'Mary Cing Sian Muang' },
      { name: 'Micheal Mang Sian Muan Thang' },
      { name: 'Monica Vung Huai Kim' },
      { name: 'Daniel Pau Sian Thawn' },
      { name: 'Theresa Cing Tawi Lun' },
    ],
    address: '14606 S Nyssa PL',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '918-720-7239',
    phoneAlt: '918-845-2593',
  },
  {
    id: 'stj-13',
    group: 'St. John',
    householdName: 'Athanasiu Vung Zuan Kham',
    members: [
      { name: 'Athanasiu Vung Zuan Kham' },
      { name: 'George Thang Lian Tuang' },
      { name: 'Ruth Cing Suan Niang' },
      { name: 'Cecilia Lun Deih Cing' },
      { name: 'Samuel Kap Za Langh' },
      { name: 'Aloysius Langh Suan Piang' },
    ],
    address: '13990 S Madison Ave',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '918-899-7464',
  },
  {
    id: 'stj-14',
    group: 'St. John',
    householdName: 'Matthew Thang Khen Kap',
    members: [
      { name: 'Matthew Thang Khen Kap' },
      { name: 'Julia Cing Khawl Nuam' },
      { name: 'Casimir Langh Sian Thang' },
      { name: 'Lucas Thang Khan Khai' },
      { name: 'Maria Ciin Lam Lun' },
      { name: 'Dominic Dal Len Thang' },
    ],
    address: '14604 S Maple Pl',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '678-362-2292',
    phoneAlt: '336-848-0609',
  },
  {
    id: 'stj-15',
    group: 'St. John',
    householdName: 'Augustine Mung Sawn Tuang',
    members: [
      { name: 'Augustine Mung Sawn Tuang' },
      { name: 'Cecilia Ciin Lam Cing' },
      { name: 'John Dal Suan Khai' },
      { name: 'Peter Nang Sawm Tung' },
    ],
    address: '1519 E 137th Pl',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '606-323-6518',
    phoneAlt: '616-965-5952',
  },
  {
    id: 'stj-16',
    group: 'St. John',
    householdName: 'Michael Nang Lam Sing',
    members: [{ name: 'Michael Nang Lam Sing' }],
    address: '1677 E 138th Pl',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '',
  },
  {
    id: 'stj-17',
    group: 'St. John',
    householdName: 'Joseph Nang Khaw Thawn',
    members: [
      { name: 'Joseph Nang Khaw Thawn' },
      { name: 'Mary Lian Lam Zam' },
      { name: 'Peter Pau Len Kop' },
      { name: 'Martha Ciang Kam Kim' },
      { name: 'Lucy Ciang Tan Lian' },
    ],
    address: '1327 E 146th St S',
    city: 'Glenpool',
    state: 'OK',
    zip: '',
    phone: '918-508-3092',
  },
  {
    id: 'stj-18',
    group: 'St. John',
    householdName: 'Aloysius Dal Za Mung (Piang Thang)',
    members: [
      { name: 'Aloysius Dal Za Mung' },
      { name: 'Esther Cing Ho Nuam' },
      { name: 'Philomena Nei Tawi Lun' },
    ],
    address: '1118 E 131st St S',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '515-500-4365',
    phoneAlt: '515-822-5745',
  },
  // ═══════════════════════════════════════
  // ST. PAUL
  // ═══════════════════════════════════════
  {
    id: 'stp-1',
    group: 'St. Paul',
    householdName: 'Fillip Dal Sing',
    members: [
      { name: 'Fillip Dal Sing' },
      { name: 'Mary Ciin Hau Muang' },
      { name: 'Monica Maan Lun' },
      { name: 'Teresa Niang San' },
      { name: 'Anna Cing Mung' },
      { name: 'Robert Cin Vaan' },
    ],
    address: '3909 W 109th St S',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '806-930-9948',
  },
  {
    id: 'stp-2',
    group: 'St. Paul',
    householdName: 'Thomas Suan Khan Kap',
    members: [
      { name: 'Thomas Suan Khan Kap' },
      { name: 'Bosco Thuam Hang' },
      { name: 'Emily Cing Tawi Nuam' },
      { name: 'Cecilia Ciin Khan Nem' },
    ],
    address: '522 W F St',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-568-8226',
    phoneAlt: '918-845-7286',
  },
  {
    id: 'stp-3',
    group: 'St. Paul',
    householdName: 'Lucas Thang Do Siam',
    members: [
      { name: 'Lucas Thang Do Siam' },
      { name: 'Marino Zam Deih Lian' },
      { name: 'Francis Thang Zam Mung' },
      { name: 'Theresa Do Nem Kim' },
      { name: 'Bibiana Ciin Ngaih Lang' },
      { name: 'Margaret Dim Huai Nuam' },
    ],
    address: '3614 W 106th St S',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-906-4640',
    phoneAlt: '918-895-5232',
  },
  {
    id: 'stp-4',
    group: 'St. Paul',
    householdName: 'Joseph Kam Tung Sang',
    members: [
      { name: 'Joseph Kam Tung Sang' },
      { name: 'Lucy Niang Ngaih Vung' },
      { name: 'Paulina Ciin San Hoih' },
      { name: 'Michael Thawng Khan Khual' },
      { name: 'John Maang KapThang' },
      { name: 'Khual Kuam Thang' },
      { name: 'Thomas Aquinas Cing Biak Suum Foustina' },
    ],
    address: '1012 N Ivy St',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-289-5593',
    phoneAlt: '919-808-6904',
  },
  {
    id: 'stp-5',
    group: 'St. Paul',
    householdName: 'Joseph Ngo Suan Pau',
    members: [
      { name: 'Joseph Ngo Suan Pau' },
      { name: 'James Thang Lam Khup' },
      { name: 'July Sian Ngaih Mang' },
      { name: 'Mary Tual Ngaih Lun' },
      { name: 'Margaret Ciin San Kiim' },
    ],
    address: '1004 W 86th Pl S',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '913-999-2446',
    phoneAlt: '913-202-4391',
  },
  {
    id: 'stp-6',
    group: 'St. Paul',
    householdName: 'Thomas Pau Lian Mang',
    members: [
      { name: 'Thomas Pau Lian Mang' },
      { name: 'Emmanuel Cin Khan Ngai' },
      { name: 'Elizabeth Vung Nem Huai' },
      { name: 'John Pau Langh Sum' },
      { name: 'Peter Zuan Sian Khai' },
      { name: 'Philip Dal Do Tungh' },
      { name: 'Magaret Mary Lun Nuam Cing' },
      { name: 'Daniel Kim Sian Thang' },
    ],
    address: '2101 W G St',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-600-8096',
    phoneAlt: '918-814-4209',
  },
  {
    id: 'stp-7',
    group: 'St. Paul',
    householdName: 'John Cin Thein Sang',
    members: [
      { name: 'John Cin Thein Sang' },
      { name: 'Augustine Hang Huam Sang' },
      { name: 'Gabriel Hau Sian Sum' },
      { name: 'Esther Cing Khawm Niang' },
      { name: 'Moses Nang Tup Dollar' },
      { name: 'Maria Lun Biak Muang' },
    ],
    address: '1624 W 110th Pl S',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-497-9037',
    phoneAlt: '918-734-2809',
  },
  {
    id: 'stp-8',
    group: 'St. Paul',
    householdName: 'Joseph Zam Cin Dal',
    members: [
      { name: 'Joseph Zam Cin Dal' },
      { name: 'Christina Cing Sian Zam' },
      { name: 'David Cing Sian Thang' },
      { name: 'Paul Nang Gin Pau' },
      { name: 'Theresa Cing Dim Vung' },
      { name: 'Michael Dim Deih Kim' },
      { name: 'Philip Cin Zam Sian Khai' },
    ],
    address: '202 E H St',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-500-8679',
    phoneAlt: '539-215-0136',
  },
  {
    id: 'stp-9',
    group: 'St. Paul',
    householdName: 'Anthony Pau Len Zang',
    members: [
      { name: 'Anthony Pau Len Zang' },
      { name: 'Lucy Lu Mai' },
      { name: 'Emily Vung Ngaih Lian' },
      { name: 'Magaret Cing Dot Nuam' },
      { name: 'Michael Kim Deih Piang' },
      { name: 'Solomon Thang Sian Muang' },
      { name: 'Anna Niang Ngaih Dim' },
    ],
    address: '3713 W 106th St S',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-565-2106',
    phoneAlt: '918-330-0783',
  },
  {
    id: 'stp-10',
    group: 'St. Paul',
    householdName: 'Robert Thang Suan Kim',
    members: [
      { name: 'Robert Thang Suan Kim' },
      { name: 'Peter Pau Za Khup' },
      { name: 'Theresa Dim Ngai Niang' },
      { name: 'Thomas Khup Ngaih' },
      { name: 'Cecilia Cing Khawl No' },
      { name: 'Michael Khai Lun Lal' },
    ],
    address: '10312 S Prescott St',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-270-3339',
  },
  {
    id: 'stp-11',
    group: 'St. Paul',
    householdName: 'Francis Lang Lian Kam',
    members: [
      { name: 'Francis Lang Lian Kam' },
      { name: 'Mary Madalenna Nem Lam Cing' },
      { name: 'Theresa Man Deih Kim' },
      { name: 'Do Kawm Siam Veronica' },
      { name: 'Cing Lun Dim Monica' },
      { name: 'Man Dot Cing Angela' },
      { name: 'Cing Nuam Nem Margaret' },
    ],
    address: '8716 S Quanah Ave West',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-734-8836',
    phoneAlt: '918-344-4979',
  },
  {
    id: 'stp-12',
    group: 'St. Paul',
    householdName: 'Maku Mang Lam Thang',
    members: [
      { name: 'Maku Mang Lam Thang' },
      { name: 'Cing Ngaih Zam Magaret Mary' },
      { name: 'Luke Zam Muan Khai' },
      { name: 'Veronica Vung Lun Kim' },
      { name: 'Dominic Khai Biak Sang' },
    ],
    address: '3705 W 106th St S',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '806-922-1081',
    phoneAlt: '806-922-6434',
  },
  {
    id: 'stp-13',
    group: 'St. Paul',
    householdName: 'Bosco Thang Khawm Mung',
    members: [
      { name: 'Bosco Thang Khawm Mung' },
      { name: 'Cecilia Hau ngaih Don' },
      { name: 'Lucy Cing San Lun' },
      { name: 'David Khup Sang' },
      { name: 'Benjamin Khen Sian Muan' },
      { name: 'Maria Vung Nuam Cing' },
    ],
    address: '10410 S Olmsted Pl',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-978-9281',
  },
  {
    id: 'stp-14',
    group: 'St. Paul',
    householdName: 'Dominic Nang Muan Lian',
    members: [
      { name: 'Dominic Nang Muan Lian' },
      { name: 'Rita Cing Sian Hoih' },
      { name: 'Regina Niiang San Dim' },
      { name: 'Christina Cing San Paak' },
      { name: 'Martha Niang Tawi It' },
      { name: 'Joseph Suan Lam Khai' },
    ],
    address: '2001 W H St',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-845-6733',
  },
  {
    id: 'stp-15',
    group: 'St. Paul',
    householdName: 'Clement Cing Theih Lian',
    members: [
      { name: 'Clement Cing Theih Lian' },
      { name: 'Cecilia Niangh Suan Lun' },
      { name: 'Monica Zen Do Nem' },
      { name: 'Mary Vung Don Nuam' },
      { name: 'Leo Piang Gel Sian' },
    ],
    address: '10372 S Nathan St',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-984-5470',
  },
  {
    id: 'stp-16',
    group: 'St. Paul',
    householdName: 'John Ngam Kho Lun Baite',
    members: [
      { name: 'John Ngam Kho Lun Baite' },
      { name: 'Robert Ngam Min Lal Baite' },
      { name: 'Mary Lal Hmu Thari Baite' },
      { name: 'Dominic Dal Len Mawi Baite' },
    ],
    address: '1212 N 2nd St',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-408-2316',
    phoneAlt: '918-361-2376',
  },
  {
    id: 'stp-17',
    group: 'St. Paul',
    householdName: 'Joseph Pau Sum Mang',
    members: [
      { name: 'Joseph Pau Sum Mang' },
      { name: 'Monica Sian Hoih' },
      { name: 'Catherine Man Sun Kim' },
      { name: 'Theresa Dim Khan Lun' },
      { name: 'Anna Man Deih Cing' },
    ],
    address: '10325 S Prescott St',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-289-9731',
    phoneAlt: '818-720-7486',
  },
  {
    id: 'stp-18',
    group: 'St. Paul',
    householdName: 'Anthony Do Khan Sum',
    members: [
      { name: 'Anthony Do Khan Sum' },
      { name: 'Man Deih Piang' },
      { name: 'Ciin Ho Nuam' },
    ],
    address: '721 W 120th Ct S',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-306-5777',
    phoneAlt: '918-900-3165',
  },
  {
    id: 'stp-19',
    group: 'St. Paul',
    householdName: 'Robert Cin Lian Zom',
    members: [
      { name: 'Robert Cin Lian Zom' },
      { name: 'Magaret Cing Khawm Huai' },
    ],
    address: '1004 W 86th Pl S',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '360-286-3656',
  },
  {
    id: 'stp-20',
    group: 'St. Paul',
    householdName: 'Paul Langh Sian Piang',
    members: [
      { name: 'Paul Langh Sian Piang' },
      { name: 'Tual Sian Lun' },
    ],
    address: '10350 S Nathan Pl',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-404-3137',
  },
  // ═══════════════════════════════════════
  // ST. JOSEPH
  // ═══════════════════════════════════════
  {
    id: 'stjos-1',
    group: 'St. Joseph',
    householdName: 'Raphael Thang Mang',
    members: [
      { name: 'Raphael Thang Mang' },
      { name: 'Maria Am Ngaih Lian' },
      { name: 'Monica Cing Sian Dim' },
      { name: 'Elizabeth Hau Zen Lun' },
      { name: 'Cecilia Cing Ngaih Ciin' },
      { name: 'Rosa Lun Deih Kim' },
    ],
    address: '4012 W 55th PL',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-581-3404',
  },
  {
    id: 'stjos-2',
    group: 'St. Joseph',
    householdName: 'James Kam Suan Mung',
    members: [
      { name: 'James Kam Suan Mung' },
      { name: 'Joanna Ciin San' },
      { name: 'Juliana Man Sian Muang' },
    ],
    address: '5140 S 34th ST Ave',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-224-4648',
    phoneAlt: '918-606-2480',
  },
  {
    id: 'stjos-3',
    group: 'St. Joseph',
    householdName: 'John Kap Suan Thang',
    members: [
      { name: 'John Kap Suan Thang' },
      { name: 'Mary Cing Hau Kim' },
      { name: 'Judith Cing Lun Niang' },
      { name: 'Cecilia Cing San Hoih' },
      { name: 'Joseph Thang Muan Khai' },
    ],
    address: '2415 W 45th Pl',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-936-5525',
    phoneAlt: '918-900-3926',
  },
  {
    id: 'stjos-4',
    group: 'St. Joseph',
    householdName: 'Stephen Pau Sian Thang',
    members: [
      { name: 'Stephen Pau Sian Thang' },
      { name: 'Mary Cing It Siam' },
      { name: 'Rose Lian Za Cing' },
      { name: 'Theresa Niang It Huai' },
      { name: 'Emily Ning Sian Ciang' },
      { name: 'Irene Thang Sian Dim' },
    ],
    address: '6307 S 28th West Ave',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-936-9877',
    phoneAlt: '918-707-0356',
  },
  {
    id: 'stjos-5',
    group: 'St. Joseph',
    householdName: 'Peter Go Ngaih Cin',
    members: [
      { name: 'Peter Go Ngaih Cin' },
      { name: 'Monica Niang Sian San' },
      { name: 'Catherine Ning Zuan Cing' },
      { name: 'Anna Cing Lian Nuam' },
      { name: 'Angela Man Sian Hoih' },
      { name: 'Elizabeth Pau Sian Muang' },
    ],
    address: '2927 W 61 St Pl',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-829-4939',
  },
  {
    id: 'stjos-6',
    group: 'St. Joseph',
    householdName: 'Mark Gin Za Tuang',
    members: [
      { name: 'Mark Gin Za Tuang' },
      { name: 'Mary Cing Lun Mang' },
    ],
    address: '3722 W 53th',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-361-3821',
  },
  {
    id: 'stjos-7',
    group: 'St. Joseph',
    householdName: 'Augustine Nang Za Thang',
    members: [
      { name: 'Augustine Nang Za Thang' },
      { name: 'Cecilia Vung Nem Lian' },
      { name: 'Anna Cing Lun Niang' },
      { name: 'Angela Cing Muan Kim' },
    ],
    address: '2709 W 65th Pl',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-269-4608',
    phoneAlt: '539-302-9355',
  },
  {
    id: 'stjos-8',
    group: 'St. Joseph',
    householdName: 'Paul Pau Suan Khai',
    members: [
      { name: 'Paul Pau Suan Khai' },
      { name: 'Thomas Thang Sian Khai' },
      { name: 'Angela Cing Sian Muan' },
      { name: 'David Thang Khan Khual' },
      { name: 'Cecilia Dim Khan Ciang' },
    ],
    address: '6438 S 28th West Ave',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-606-8335',
  },
  {
    id: 'stjos-9',
    group: 'St. Joseph',
    householdName: 'Joseph Kam Kim Mang',
    members: [
      { name: 'Joseph Kam Kim Mang' },
      { name: 'Elizabeth Kim San Huai' },
      { name: 'John Pau Deih Lian' },
      { name: 'Martha Ning Suan Muan' },
      { name: 'Michael Tung Kim Sing' },
      { name: 'Thomas Thang Sian Khai' },
      { name: 'Theresa Man Ngaih Don' },
      { name: 'Magaret Cing Sian Nuam' },
    ],
    address: '6414 S 28th W Ave',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-640-9729',
    phoneAlt: '918-829-4008',
  },
  {
    id: 'stjos-10',
    group: 'St. Joseph',
    householdName: 'Albert Thang Khan Khai',
    members: [
      { name: 'Albert Thang Khan Khai' },
      { name: 'Joseph En Hon Thang' },
      { name: 'Francis Sum Muan Mung' },
      { name: 'Monica Zen Lam Dim' },
      { name: 'John Baptist Thang Sian Deih Piang' },
    ],
    address: '3806 W 55th Pl',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-219-9244',
    phoneAlt: '918-902-4019',
  },
  {
    id: 'stjos-11',
    group: 'St. Joseph',
    householdName: 'Augustine Thang Suan Tuang',
    members: [
      { name: 'Augustine Thang Suan Tuang' },
      { name: 'William Hau Sian Suum' },
      { name: 'Emma Sian Nu' },
      { name: 'Anna Niang Sian Nem' },
      { name: 'Rosa Mang Sian Muang' },
    ],
    address: '4016 W 43rd St',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-576-4778',
    phoneAlt: '918-576-8039',
  },
  {
    id: 'stjos-12',
    group: 'St. Joseph',
    householdName: 'Joseph Kai Suan Mung',
    members: [{ name: 'Joseph Kai Suan Mung' }],
    address: '3708 W 54th St',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-269-3371',
    phoneAlt: '918-704-2927',
  },
  {
    id: 'stjos-13',
    group: 'St. Joseph',
    householdName: 'Dominic Khual Theih Lian',
    members: [
      { name: 'Dominic Khual Theih Lian' },
      { name: 'Esther Lun Go Dim' },
    ],
    address: '2940 W 66th St',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-264-6472',
  },
  {
    id: 'stjos-14',
    group: 'St. Joseph',
    householdName: 'Augustine Khup Khen Khai',
    members: [
      { name: 'Augustine Khup Khen Khai' },
      { name: 'Dominic Pau Sian Mang' },
      { name: 'Cecilia No Lun Cing' },
      { name: 'Theresa Ning Ngaih Mang' },
      { name: 'John Pau Muan Lian' },
    ],
    address: '6447 S 28th West Ave',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-398-1773',
  },
  {
    id: 'stjos-15',
    group: 'St. Joseph',
    householdName: 'John Nang Kap Lian',
    members: [
      { name: 'John Nang Kap Lian' },
      { name: 'Michael Zam Sian Langh' },
      { name: 'Esther Lun Sian Nem' },
      { name: 'Augustine Suan Deih Tung' },
      { name: 'Mary Man Sian Niang' },
      { name: 'Elizabeth Zam Lun Dim' },
    ],
    address: '2933 W 66th St',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-520-6177',
    phoneAlt: '918-852-8076',
  },
  {
    id: 'stjos-16',
    group: 'St. Joseph',
    householdName: 'John Go Za Dal',
    members: [{ name: 'John Go Za Dal' }],
    address: '6441 S 32nd W Ave',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-430-8343',
  },
  {
    id: 'stjos-17',
    group: 'St. Joseph',
    householdName: 'Peter Khup Khen Hang',
    members: [
      { name: 'Peter Khup Khen Hang' },
      { name: 'Bibiana Niang Suan Lun' },
    ],
    address: '7857 S Utica Ave Apt B',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-998-3017',
  },
  {
    id: 'stjos-18',
    group: 'St. Joseph',
    householdName: 'Peter Thang Sian Piang',
    members: [
      { name: 'Peter Thang Sian Piang' },
      { name: 'Theresa Zen Hau Vung' },
      { name: 'Peter Mung Van Tung' },
    ],
    address: '6244 S 31st W Ave',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-704-2927',
  },
  {
    id: 'stjos-19',
    group: 'St. Joseph',
    householdName: 'Vincent Do Sian Mang',
    members: [
      { name: 'Vincent Do Sian Mang' },
      { name: 'Monica Dim Sen Nuam' },
      { name: 'Michael Dal Mun Van' },
      { name: 'Theresa Do Tawi Cing' },
      { name: 'Cecilia Vung Sian Kim' },
      { name: 'Cing Lam Mung' },
    ],
    address: '2810 W 64th St S',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '270-779-3367',
    phoneAlt: '270-421-5901',
  },
  {
    id: 'stjos-20',
    group: 'St. Joseph',
    householdName: 'Anthony Cin Sian Sang',
    members: [{ name: 'Anthony Cin Sian Sang' }],
    address: '3817 S 29th W Ave',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-706-6489',
  },
  {
    id: 'stjos-21',
    group: 'St. Joseph',
    householdName: 'Raphael Dal Suan Piang',
    members: [
      { name: 'Raphael Dal Suan Piang' },
      { name: 'Theresa Kim Ngaih Lian' },
      { name: 'Esther Lian Man Niang' },
      { name: 'Francis Kam Khan Thawn' },
    ],
    address: '6219 S 29th West Ave',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-605-2635',
  },
  {
    id: 'stjos-22',
    group: 'St. Joseph',
    householdName: 'Marcus Thang Sian Khua Vak',
    members: [
      { name: 'Marcus Thang Sian Khua Vak' },
      { name: 'Gorettia Lam Go Cing Maria' },
      { name: 'Paul Khup Deih Tung' },
      { name: 'Peter Kham Sian Muan' },
    ],
    address: '2744 W 66th St',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '832-949-1711',
  },
  // ═══════════════════════════════════════
  // ST. PETER
  // ═══════════════════════════════════════
  {
    id: 'stpet-1',
    group: 'St. Peter',
    householdName: 'Saw Khu',
    members: [
      { name: 'Saw Khu' },
      { name: 'Mary Christina Kyaw' },
      { name: 'Victoria Anna Khu' },
      { name: 'Monica Ngaih Ngaih' },
      { name: 'Monica Honey Kyaw' },
      { name: 'Elizabeth Naw Haannah Lun' },
    ],
    address: '1219 W 118th St S',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-927-8379',
  },
  {
    id: 'stpet-2',
    group: 'St. Peter',
    householdName: 'Peter Kam Do Khen',
    members: [
      { name: 'Peter Kam Do Khen' },
      { name: 'Michael Mang Cin Khup' },
      { name: 'Theresa Lun Sian Nuam' },
      { name: 'Veronica Awi Dim Lun' },
      { name: 'Stephen Gin Dot Muang' },
      { name: 'Paul Kam Cin Thang' },
      { name: 'Vicent Khen Sawm Sang' },
      { name: 'Lucy Cing Sian Hoih' },
      { name: 'Peter Kap Tuang' },
    ],
    address: '1724 W 115th PL',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-630-3172',
  },
  {
    id: 'stpet-3',
    group: 'St. Peter',
    householdName: 'Michael Mang Lian Tual',
    members: [
      { name: 'Michael Mang Lian Tual' },
      { name: 'Martha Nuam Suan Cing' },
      { name: 'Augustine Kham Muan Sian' },
      { name: 'Monica Ning Nih Ngaih' },
      { name: 'Joanna Ciin Lun Niang' },
      { name: 'Lucy Pau Hau Vung' },
    ],
    address: '11916 S Gum Ave',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-209-1936',
    phoneAlt: '918-209-1661',
  },
  {
    id: 'stpet-4',
    group: 'St. Peter',
    householdName: 'Alphonse Kam Sian Pau',
    members: [
      { name: 'Alphonse Kam Sian Pau' },
      { name: 'Anna Cing Deih Piang' },
      { name: 'Paul Khup Tel' },
      { name: 'Esther Ciin Suan Sang' },
      { name: 'Gabriel Pau Khai' },
      { name: 'Elizabeth Dim Lawh Nuam' },
      { name: 'Ruth Zam Dim' },
    ],
    address: '11916 S Holley St',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-813-8896',
  },
  {
    id: 'stpet-5',
    group: 'St. Peter',
    householdName: 'Anthony Cin Lian Khup',
    members: [
      { name: 'Anthony Cin Lian Khup' },
      { name: 'Rita Niang Zam Cing' },
    ],
    address: '601 W 118th St',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-210-9758',
    phoneAlt: '918-557-5040',
  },
  {
    id: 'stpet-6',
    group: 'St. Peter',
    householdName: 'Peter Cin Sum Mang',
    members: [
      { name: 'Peter Cin Sum Mang' },
      { name: 'Maria Cing Sian Muang' },
      { name: 'Esther Sang Ngaih Lian' },
      { name: 'Lucia Zam Suan Lun' },
      { name: 'Anna Cing Saan Kim' },
    ],
    address: '709 W 119th PL S',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-428-8360',
    phoneAlt: '539-215-4229',
  },
  {
    id: 'stpet-7',
    group: 'St. Peter',
    householdName: 'John Lam Lian Thang',
    members: [
      { name: 'John Lam Lian Thang' },
      { name: 'Cecilia Cing Khawl Nuam' },
      { name: 'Monica Dim Sawm Cing' },
      { name: 'Francis Kam Sian Muan' },
      { name: 'Maria Man Ngaih Lian' },
      { name: 'Maria Zam Ngel Sang' },
    ],
    address: '1013 W 117th St S',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-727-4234',
    phoneAlt: '331-454-1466',
  },
  {
    id: 'stpet-8',
    group: 'St. Peter',
    householdName: 'Peter Dal Za Pau',
    members: [
      { name: 'Peter Dal Za Pau' },
      { name: 'Adela Cing San Nuam' },
      { name: 'Monica Cing Sian Sei' },
      { name: 'Angela Man Suan Kim' },
      { name: 'Anna Lun Suan Huai' },
    ],
    address: '2015 W 119th Ct S',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-895-5762',
    phoneAlt: '918-691-8234',
  },
  {
    id: 'stpet-9',
    group: 'St. Peter',
    householdName: 'Ko Thet',
    members: [
      { name: 'Ko Thet' },
      { name: 'Rosa Niang Deih Li' },
      { name: 'Mary Cing San Zun' },
      { name: 'Olivia Cing Sian Lun' },
      { name: 'Esther Dal Sian Muang' },
    ],
    address: '11259 S Franklin Ave',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '585-465-7637',
  },
  {
    id: 'stpet-10',
    group: 'St. Peter',
    householdName: 'Anthony Pum Lam Tuang',
    members: [
      { name: 'Anthony Pum Lam Tuang' },
      { name: 'Fedelik Lian Khan Lun' },
      { name: 'Anna Thang Deih Tung' },
      { name: 'Simon Thang Suan Tuang' },
      { name: 'Mary Cing Sian Mun Muang' },
      { name: 'Lucy Hau Muan Kim' },
      { name: 'Julia Lun Sian Sang' },
      { name: 'Rose Thang Biak Mawi' },
      { name: 'Regina Mang Muan Lian' },
      { name: 'John Thang Khan Kim' },
      { name: 'Noah' },
    ],
    address: '1902 W 117th PL S',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-402-8726',
    phoneAlt: '915-442-4159',
  },
  {
    id: 'stpet-11',
    group: 'St. Peter',
    householdName: 'Francis Khai Lam Khup',
    members: [
      { name: 'Francis Khai Lam Khup' },
      { name: 'Mate Tai Kap Za Sang' },
      { name: 'Rita Man Dim Lun' },
      { name: 'John Kam Sian Mang' },
      { name: 'Peter Thang Thawn Tuang' },
      { name: 'Anna Man Deih Vung' },
      { name: 'Paul Dal Khua Sai' },
      { name: 'Samuel Dal Tel Kim Siam' },
    ],
    address: '1426 W 118th St S',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-902-6601',
  },
  {
    id: 'stpet-12',
    group: 'St. Peter',
    householdName: 'Michael Gen Khan Sut',
    members: [
      { name: 'Michael Gen Khan Sut' },
      { name: 'Esther Dim Nem Vung' },
      { name: 'Monica Don Lam Tang' },
    ],
    address: '12512 S Date PL',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '806-437-6490',
    phoneAlt: '806-477-8435',
  },
  {
    id: 'stpet-13',
    group: 'St. Peter',
    householdName: 'Victor Hau Langh Zam',
    members: [
      { name: 'Victor Hau Langh Zam' },
      { name: 'Christina Gin Zam Cing' },
      { name: 'Gualatee Lun San Nuam Maria' },
      { name: 'Scholartica Dim San Kim' },
      { name: 'Benedict Kap Kim Tuang' },
    ],
    address: '285 Fox Run Circle',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '402-405-1872',
  },
  {
    id: 'stpet-14',
    group: 'St. Peter',
    householdName: 'John Suan Mungpi',
    members: [{ name: 'John Suan Mungpi' }],
    address: '1609 W 119th St S',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-629-9026',
  },
  {
    id: 'stpet-15',
    group: 'St. Peter',
    householdName: 'Anthony Mang Mun Khai',
    members: [
      { name: 'Anthony Mang Mun Khai' },
      { name: 'Huai Lam Cing' },
      { name: 'Joseph Pau Phut Mung' },
      { name: 'Enoch Mang Sian Khual' },
    ],
    address: '181 W 113th Ct S',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '832-282-6562',
  },
  {
    id: 'stpet-16',
    group: 'St. Peter',
    householdName: 'Paul Kai Teel Pau',
    members: [
      { name: 'Paul Kai Teel Pau' },
      { name: 'Cecilia Pau Ngaih No' },
      { name: 'Elizabeth Niang Ngaih Dim' },
      { name: 'Jacob Kap Cin Siam' },
      { name: 'Joseph Thang Mun Khai' },
      { name: 'Rose Niang Sian Lun' },
    ],
    address: '11806 S Ivy St',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-640-6142',
  },
  {
    id: 'stpet-17',
    group: 'St. Peter',
    householdName: 'Isidore Nang Than Lian',
    members: [
      { name: 'Isidore Nang Than Lian' },
      { name: 'Esther Khup San Par' },
      { name: 'Francis Thawn Sian Muan' },
      { name: 'Joseph Thang Lian Mang' },
      { name: 'Theresa Nem San Kim' },
      { name: 'Julia Lian Sian Huai' },
    ],
    address: '2412 W 119th St S',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-499-0122',
  },
  {
    id: 'stpet-18',
    group: 'St. Peter',
    householdName: 'Paul Pau Cin',
    members: [
      { name: 'Paul Pau Cin' },
      { name: 'Clare Ning Khan Hau' },
      { name: 'Peter Pum Hawm Thang' },
      { name: 'Joseph Pau Sian Thawn' },
      { name: 'Robert Thang Suan Gin' },
      { name: 'Noel Khup Sian Muang' },
      { name: 'Jacinta Zam Sian Cing' },
      { name: 'Esther Dim Tawi Kim' },
      { name: 'Faustina Hau Siankop' },
    ],
    address: '1905 W 117th Ct S',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-852-7936',
    phoneAlt: '918-896-2040',
  },
  {
    id: 'stpet-19',
    group: 'St. Peter',
    householdName: 'Peter Lianpu',
    members: [{ name: 'Peter Lianpu' }],
    address: '1113 W 119th St PL',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-408-0571',
  },
  {
    id: 'stpet-20',
    group: 'St. Peter',
    householdName: 'Anthony Nang Sian Piang',
    members: [{ name: 'Anthony Nang Sian Piang' }],
    address: '11706 S Holley Ct W',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-851-9470',
  },
  {
    id: 'stpet-21',
    group: 'St. Peter',
    householdName: 'Donbosco Thang Sian Lal',
    members: [
      { name: 'Donbosco Thang Sian Lal' },
      { name: 'Elizabeth Niang Ngaih Dim' },
      { name: 'Agatha Lian Mun Nuam' },
      { name: 'Cecilia Kim Nun Hoih' },
      { name: 'Lucia Ciin Sian Huam' },
    ],
    address: '1108 W 117th Ct S',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '806-451-8000',
  },
  {
    id: 'stpet-22',
    group: 'St. Peter',
    householdName: 'John Thang Kim Khai',
    members: [{ name: 'John Thang Kim Khai' }],
    address: '513 N Fir St',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '206-488-9607',
  },
  {
    id: 'stpet-23',
    group: 'St. Peter',
    householdName: 'Cecilia Deihta',
    members: [{ name: 'Cecilia Deihta' }],
    address: '724 W 119th St S',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-633-9861',
  },
  {
    id: 'stpet-24',
    group: 'St. Peter',
    householdName: 'Elizabeth Zen Sian Kim',
    members: [
      { name: 'Elizabeth Zen Sian Kim' },
      { name: 'David Pau Deih Piang' },
      { name: 'Teresa Cing Tawi Siam' },
      { name: 'John Thang Suan Mung' },
    ],
    address: '11117 S Birch St',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-688-3154',
    phoneAlt: '575-636-7759',
  },
  // ═══════════════════════════════════════
  // N/A
  // ═══════════════════════════════════════
  {
    id: 'na-1',
    group: 'N/A',
    householdName: 'Anthony Nang Zam Cin Ngaihte',
    members: [
      { name: 'Anthony Nang Zam Cin Ngaihte' },
      { name: 'Cecilia Ngai Deih Lun Ngaihte' },
      { name: 'Rose Ciin Ngaih Vung' },
      { name: 'Jude Thang Sian Za Khual Ngaihte' },
    ],
    address: '14323 Mountainview Road',
    city: 'Mansfield',
    state: 'AR',
    zip: '',
    phone: '918-644-5250',
    phoneAlt: '918-804-4646',
  },
  {
    id: 'na-2',
    group: 'N/A',
    householdName: 'Gregory Kap Suan Lian Ngaihte',
    members: [
      { name: 'Gregory Kap Suan Lian Ngaihte' },
      { name: 'Annunciata Ciin Sang Mang' },
      { name: 'Joseph Thang Sian Muan Mung Ngaihte' },
    ],
    address: '922 S West Oks',
    city: 'Stillwater',
    state: 'OK',
    zip: '',
    phone: '918-200-1771',
    phoneAlt: '405-762-3173',
  },
  {
    id: 'na-3',
    group: 'N/A',
    householdName: 'John Nang Lam Thawng',
    members: [
      { name: 'John Nang Lam Thawng' },
      { name: 'Cecilia Niang Deih Lun' },
      { name: 'Joseph Thang Mun Khual' },
      { name: 'James Dal Sian Sang' },
    ],
    address: '723 N Gillette Ave',
    city: 'Tulsa',
    state: 'OK',
    zip: '',
    phone: '918-813-6805',
    phoneAlt: '918-815-0858',
  },
  {
    id: 'na-4',
    group: 'N/A',
    householdName: 'Joseph Pau Sian Sang',
    members: [
      { name: 'Joseph Pau Sian Sang' },
      { name: 'Cecilia Khawm Lam Ciin' },
      { name: 'Josephine Teel Sian Huai' },
      { name: 'Peter Thang San Sian Lian' },
      { name: 'John Lang Thawn Kim' },
    ],
    address: '5012 N Nancy lee Dr',
    city: 'Stillwater',
    state: 'OK',
    zip: '',
    phone: '918-399-8212',
  },
  {
    id: 'na-5',
    group: 'N/A',
    householdName: 'Robert Khup Geel Mung',
    members: [
      { name: 'Robert Khup Geel Mung' },
      { name: 'Helena Niang Khawm Huai' },
      { name: 'Emily Niang Gin Cing' },
      { name: 'Joseph Pau Sawm Thang' },
      { name: 'Monica Niang Suan Lian' },
    ],
    address: '317 N Cedar St',
    city: 'Jenks',
    state: 'OK',
    zip: '',
    phone: '918-946-6245',
    phoneAlt: '918-939-9618',
  },
];
